spring:
  application:
    name: Task-Management-System

  datasource:
    url: jdbc:postgresql://localhost:5436/postgres
    username: admin
    password: admin

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migrations
    clean-disabled: true

  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    org:
      flywaydb:
        DEBUG
